// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea_Seis_y_Siete.Data;

namespace Tarea_Seis_y_Siete.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201102200927_Database Creation")]
    partial class DatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Tarea_Seis_y_Siete.Data.Tesoro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitud")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitud")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lugar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<string>("URLReferencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCorreo")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioCorreo");

                    b.ToTable("Tesoros");
                });

            modelBuilder.Entity("Tarea_Seis_y_Siete.Data.Usuario", b =>
                {
                    b.Property<string>("Correo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorFav")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Correo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Tarea_Seis_y_Siete.Data.Tesoro", b =>
                {
                    b.HasOne("Tarea_Seis_y_Siete.Data.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioCorreo");
                });
#pragma warning restore 612, 618
        }
    }
}
